---
name: Bug Report (ring-client-api)
about: Report a bug in ring-client-api
labels: 'bug'
---

<!--
Please DO NOT DELETE THIS TEMPLATE or your issue may be closed immediately.
Before opening an issue, search for open and closed GitHub issues that match your situation.

If this is a Live Stream issue please go back and use the Live Streaming issue template.
-->

# Bug Report

### Describe the Bug
<!-- ✍️edit: --> A clear and concise description of the problem...

### To Reproduce
Steps to reproduce the behavior:
 - Create an `ApiClient`
 - Attempt to ...
 - See error

### Expected behavior
<!-- ✍️edit: --> A clear and concise description of what you expected to happen.


### Screenshots/Logs
<!-- ✍️edit: --> If applicable, add screenshots and log output to help explain your problem.

### Additional context
<!-- ✍️edit: --> Add any other context about the problem here.

### Environment
<!-- ✍️edit: -->
 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] <!-- run `node -v` to get current version -->
 - NPM: [e.g 6.13.4] <!-- run `npm -v` to get current version -->
 - ring-client-api: [e.g 6.0.3]
