---
name: Bug Report (homebridge-ring)
about: Report a bug in homebridge-ring
labels: 'bug'
---

<!--
Please DO NOT DELETE THIS TEMPLATE or your issue may be closed immediately.
Before opening an issue, search for open and closed GitHub issues that match your situation.

If this is a Live Stream issue please go back and use the Live Streaming issue template.
-->

# Bug Report

### Describe the Bug
<!-- ✍️edit: --> A clear and concise description of the problem...

### To Reproduce
Steps to reproduce the behavior:
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
<!-- ✍️edit: --> A clear and concise description of what you expected to happen.


### Screenshots/Logs
<!-- ✍️edit: --> If applicable, add screenshots and log output to help explain your problem.

### Additional context
<!-- ✍️edit: --> Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment
<!-- ✍️edit: -->
 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] <!-- run `node -v` to get current version -->
 - NPM: [e.g 6.13.4] <!-- run `npm -v` to get current version -->
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]
