---
name: Feature Request
about: Suggest an idea for this project
labels: 'enhancement'
---
<!--
Please DO NOT DELETE THIS TEMPLATE or your issue may be closed immediately.
Before opening an issue, search for open and closed GitHub issues that match your request.
-->

# Feature Request

### Description
<!-- ✍️--> A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
<!-- ✍️--> If you have a solution in mind, please describe it.

### Describe alternatives you've considered
<!-- ✍️--> Have you considered any alternative solutions or workarounds?

### Device data
<!-- ✍️-->  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here
